###########################################################
##                                                       ##
##        EP1 de MAC0422 - Sistemas Operacionais         ##
##                                                       ##
##         B'arbara de Castro Fernandes -7577351          ##
##         Mauricio Luiz Abreu Cardoso - 6796479         ##
##                                                       ##
###########################################################

CFLAGS = -Wall -pedantic -O2 -ansi

mac422shell: mac422shell.c comandos.c leitura.c
